/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface GsGifsearch {
    'apiKey': string;
    'gifsPerPage': number;
  }
  interface GsGifsearchAttributes extends StencilHTMLAttributes {
    'apiKey'?: string;
    'gifsPerPage'?: number;
  }

  interface GsSearchbox {}
  interface GsSearchboxAttributes extends StencilHTMLAttributes {
    'onSubmit-search'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'GsGifsearch': Components.GsGifsearch;
    'GsSearchbox': Components.GsSearchbox;
  }

  interface StencilIntrinsicElements {
    'gs-gifsearch': Components.GsGifsearchAttributes;
    'gs-searchbox': Components.GsSearchboxAttributes;
  }


  interface HTMLGsGifsearchElement extends Components.GsGifsearch, HTMLStencilElement {}
  var HTMLGsGifsearchElement: {
    prototype: HTMLGsGifsearchElement;
    new (): HTMLGsGifsearchElement;
  };

  interface HTMLGsSearchboxElement extends Components.GsSearchbox, HTMLStencilElement {}
  var HTMLGsSearchboxElement: {
    prototype: HTMLGsSearchboxElement;
    new (): HTMLGsSearchboxElement;
  };

  interface HTMLElementTagNameMap {
    'gs-gifsearch': HTMLGsGifsearchElement
    'gs-searchbox': HTMLGsSearchboxElement
  }

  interface ElementTagNameMap {
    'gs-gifsearch': HTMLGsGifsearchElement;
    'gs-searchbox': HTMLGsSearchboxElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
