/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface GsGiflist {
    'gifs': any;
  }
  interface GsGiflistAttributes extends StencilHTMLAttributes {
    'gifs'?: any;
  }

  interface GsGifsearch {}
  interface GsGifsearchAttributes extends StencilHTMLAttributes {}

  interface GsSearchbox {}
  interface GsSearchboxAttributes extends StencilHTMLAttributes {
    'onSubmit-search'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'GsGiflist': Components.GsGiflist;
    'GsGifsearch': Components.GsGifsearch;
    'GsSearchbox': Components.GsSearchbox;
  }

  interface StencilIntrinsicElements {
    'gs-giflist': Components.GsGiflistAttributes;
    'gs-gifsearch': Components.GsGifsearchAttributes;
    'gs-searchbox': Components.GsSearchboxAttributes;
  }


  interface HTMLGsGiflistElement extends Components.GsGiflist, HTMLStencilElement {}
  var HTMLGsGiflistElement: {
    prototype: HTMLGsGiflistElement;
    new (): HTMLGsGiflistElement;
  };

  interface HTMLGsGifsearchElement extends Components.GsGifsearch, HTMLStencilElement {}
  var HTMLGsGifsearchElement: {
    prototype: HTMLGsGifsearchElement;
    new (): HTMLGsGifsearchElement;
  };

  interface HTMLGsSearchboxElement extends Components.GsSearchbox, HTMLStencilElement {}
  var HTMLGsSearchboxElement: {
    prototype: HTMLGsSearchboxElement;
    new (): HTMLGsSearchboxElement;
  };

  interface HTMLElementTagNameMap {
    'gs-giflist': HTMLGsGiflistElement
    'gs-gifsearch': HTMLGsGifsearchElement
    'gs-searchbox': HTMLGsSearchboxElement
  }

  interface ElementTagNameMap {
    'gs-giflist': HTMLGsGiflistElement;
    'gs-gifsearch': HTMLGsGifsearchElement;
    'gs-searchbox': HTMLGsSearchboxElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
